stages:
  - build
  - package
  - release

variables:
  # Dotnet
  DOTNET_CLI_HOME: "$CI_PROJECT_DIR/.dotnet-home"
  # Nuget
  NUGET_PACKAGES: "$CI_PROJECT_DIR/.nuget/packages"

# SDK Install
.dotnet:
  image: "$DOTNET_SDK_IMAGE"
  before_script:
    - mkdir -p "$DOTNET_CLI_HOME" "$NUGET_PACKAGES"
    - dotnet --info

# Build Client
build:client:linux:
  extends: .dotnet
  stage: build
  tags:
    - ubuntu-docker
  parallel: 
    matrix:
      - ARCH: [x64, arm, arm64]
  script: 
    - cd ./VoiceCraft.Client/VoiceCraft.Client.Linux
    - dotnet workload restore
    - dotnet publish -c Release -r linux-$ARCH -p:PublishSingleFile=true -o "$CI_PROJECT_DIR/VoiceCraft.Client.Linux.$ARCH"
  artifacts:
    name: "VoiceCraft.Client.Linux.$ARCH"
    expire_in: 14 days
    paths:
      - VoiceCraft.Client.Linux.$ARCH/