stages:
  - test
  - build
  - package
  - release

variables:
  # Dotnet
  DOTNET_SDK_IMAGE: "registry-gitlab.avion.team/voicecraft/voicecraft.build:latest"
  DOTNET_CLI_HOME: "$CI_PROJECT_DIR/.dotnet-home"
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_NOLOGO: "true"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
  DOTNET_CLI_UI_LANGUAGE: "en"
  MSBuildEnableWorkloadResolver: "false"
  NUGET_CLI_LANGUAGE: "en"
  GIT_CLEAN_FLAGS: "-ffdx -e .nuget/"
  # Nuget
  NUGET_PACKAGES: "$CI_PROJECT_DIR/.nuget/packages"
  
# SDK Install
.dotnet:
  image: "$DOTNET_SDK_IMAGE"

.dotnet:linux:
  extends: .dotnet
  cache:
    key:
      files:
        - Directory.Packages.props
      prefix: nuget-linux
    paths:
      - .nuget/packages/
    policy: pull
  before_script:
    - mkdir -p "$DOTNET_CLI_HOME" "$NUGET_PACKAGES"
    - dotnet --version

.dotnet:windows:
  extends: .dotnet
  before_script:
    - $env:DOTNET_CLI_HOME = Join-Path $env:CI_PROJECT_DIR ".dotnet-home"
    - $env:NUGET_PACKAGES = Join-Path $env:CI_PROJECT_DIR ".nuget\packages"
    - New-Item -ItemType Directory -Force -Path $env:DOTNET_CLI_HOME, $env:NUGET_PACKAGES | Out-Null
    - dotnet --version
  
# Tests
.test:
  stage: test
  script:
    - dotnet test ./VoiceCraft.Core.Tests/VoiceCraft.Core.Tests.csproj -c Release -p:UseSharedCompilation=false --collect:"XPlat Code Coverage" --logger "junit;LogFileName=junit.xml" --results-directory TestResults/Core
    - dotnet test ./VoiceCraft.Network.Tests/VoiceCraft.Network.Tests.csproj -c Release -p:UseSharedCompilation=false --collect:"XPlat Code Coverage" --logger "junit;LogFileName=junit.xml" --results-directory TestResults/Network
    - dotnet test ./VoiceCraft.Client.Tests/VoiceCraft.Client.Tests.csproj -c Release -p:UseSharedCompilation=false --collect:"XPlat Code Coverage" --logger "junit;LogFileName=junit.xml" --results-directory TestResults/Client
    - dotnet test ./VoiceCraft.Server.Runtime.Tests/VoiceCraft.Server.Runtime.Tests.csproj -c Release -p:UseSharedCompilation=false --collect:"XPlat Code Coverage" --logger "junit;LogFileName=junit.xml" --results-directory TestResults/Server
  artifacts:
    when: always
    expire_in: 14 days
    paths:
      - TestResults/
    reports:
      junit: TestResults/**/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: TestResults/**/coverage.cobertura.xml

test:linux:
  extends:
    - .dotnet:linux
    - .test
  stage: test
  tags:
    - ubuntu-docker
  cache:
    key:
      files:
        - Directory.Packages.props
      prefix: nuget-linux
    paths:
      - .nuget/packages/
    policy: pull-push

test:windows:
  extends:
    - .dotnet:windows
    - .test
  stage: test
  tags:
    - windows-shell

# Build Client
build:client:linux:
  extends: .dotnet:linux
  stage: build
  tags:
    - ubuntu-docker
  parallel: 
    matrix:
      - ARCH: [x64, arm, arm64]
  script: 
    - cd ./VoiceCraft.Client/VoiceCraft.Client.Linux
    - dotnet restore -r linux-$ARCH
    - dotnet publish -c Release -r linux-$ARCH -p:PublishSingleFile=true -p:UseSharedCompilation=false -o "$CI_PROJECT_DIR/VoiceCraft.Client.Linux.$ARCH"
  artifacts:
    name: "VoiceCraft.Client.Linux.$ARCH"
    expire_in: 14 days
    paths:
      - VoiceCraft.Client.Linux.$ARCH/
    
build:client:windows:
  extends: .dotnet:windows
  stage: build
  tags:
    - windows-shell
  parallel:
    matrix:
      - ARCH: [x64, x86, arm64]
  script:
    - cd ./VoiceCraft.Client/VoiceCraft.Client.Windows
    - dotnet restore -r "win-$env:ARCH"
    - dotnet publish -c Release -r "win-$env:ARCH" -p:PublishSingleFile=true -p:UseSharedCompilation=false -o "$env:CI_PROJECT_DIR\VoiceCraft.Client.Windows.$env:ARCH"
    - $uri = "https://aka.ms/vc14/vc_redist.$env:ARCH.exe"
    - $outFile = Join-Path $env:CI_PROJECT_DIR "VoiceCraft.Client.Windows.$env:ARCH\vc_redist.$env:ARCH.exe"
    - Invoke-WebRequest -Uri $uri -OutFile $outFile
  artifacts:
    name: "VoiceCraft.Client.Windows.$ARCH"
    expire_in: 14 days
    paths:
      - VoiceCraft.Client.Windows.$ARCH/
    exclude:
      - VoiceCraft.Client.Windows.$ARCH/*.pdb
