<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <IsAotCompatible>true</IsAotCompatible>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
        <AvaloniaResource Include="Themes\Dark\Colors.axaml.cs"/>

        <TrimmerRootAssembly Include="Avalonia.Themes.Fluent"/>
        <TrimmerRootAssembly Include="Avalonia.Themes.Default"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Themes.Fluent"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="DiscordRichPresence"/>
        <PackageReference Include="Fleck"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="Microsoft.Maui.Essentials"/>
        <PackageReference Include="OpusSharp"/>
        <PackageReference Include="SoundFlow" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\VoiceCraft.Core\VoiceCraft.Core.csproj"/>
        <ProjectReference Include="..\..\VoiceCraft.Network\VoiceCraft.Network.csproj" />
        <ProjectReference Include="..\..\VoiceCraft.Server.Runtime\VoiceCraft.Server.Runtime.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\Home\HostServerView.axaml.cs">
        <DependentUpon>HostView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\HostServerConsoleView.axaml.cs">
        <DependentUpon>ErrorView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Error\ErrorView.axaml.cs">
        <DependentUpon>HostServerConsoleView.axaml</DependentUpon>
      </Compile>
    </ItemGroup>
</Project>
