name: BuildTest
on:
   pull_request:
      branches: [ "dev", "features/dev_actions" ]
   workflow_dispatch:

jobs:
   build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./VoiceCraft.Client/VoiceCraft.Client.Android
    steps:
      - uses: actions/checkout@v4
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Install VoiceCraft.Client.Android WorkLoads
        run: dotnet workload restore

      - name: Setup Keystore File
        run: echo -n "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode >> android.keystore

      - name: Publish VoiceCraft.Client.Android.arm64
        run: dotnet publish -c Release -r arm64 --self-contained false -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=./android.keystore -p:AndroidSigningKeyAlias=${{ secrets.ALIAS }} -p:AndroidSigningKeyPass=${{ secrets.KEYSTORE_PASSWORD }} -p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }}
      - name: Upload Artifact VoiceCraft.Client.Android.arm64
        uses: actions/upload-artifact@v4
        with:
          name: VoiceCraft.Client.Android.arm64
          path: ./VoiceCraft.Client/VoiceCraft.Client.Android/bin/Debug/net9.0-android/arm64/publish/
