name: BuildTest
on: []
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install VoiceCraft.Core Dependencies
        run: dotnet workload restore ./VoiceCraft.Core/VoiceCraft.Core.csproj
      - name: Build VoiceCraft.Core
        run: dotnet build ./VoiceCraft.Core/VoiceCraft.Core.csproj

      - name: Install VoiceCraft.Network Dependencies
        run: dotnet workload restore ./VoiceCraft.Network/VoiceCraft.Network.csproj
      - name: Build VoiceCraft.Network
        run: dotnet build ./VoiceCraft.Network/VoiceCraft.Network.csproj

      - name: Install VoiceCraft.Server Dependencies
        run: dotnet workload restore ./VoiceCraft.Server/VoiceCraft.Server.csproj
      - name: Build VoiceCraft.Server
        run: dotnet build ./VoiceCraft.Server/VoiceCraft.Server.csproj
