name: BuildTest
on:
   pull_request:
      branches: [ "dev" ]
   workflow_dispatch:
   
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install VoiceCraft.Client.Windows WorkLoads
        run: dotnet workload restore ./VoiceCraft.Client/VoiceCraft.Client.Windows/VoiceCraft.Client.Windows.csproj
      - name: Build VoiceCraft.Client.Windows
        run: dotnet build ./VoiceCraft.Client/VoiceCraft.Client.Windows/VoiceCraft.Client.Windows.csproj
